name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: flightdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: flight-frontend
        run: npm install

      - name: Run frontend tests (Jest)
        working-directory: flight-frontend
        run: npm test -- --watchAll=false

      - name: Build frontend
        working-directory: flight-frontend
        run: npm run build

      - name: Install Cypress
        working-directory: flight-frontend
        run: npm install --save-dev cypress

      - name: Run Cypress E2E tests
        working-directory: flight-frontend
        run: npx cypress run

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.3

      - name: Install backend dependencies
        working-directory: flight_backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        working-directory: flight_backend
        run: python manage.py test


